import image1 from "./customer-images/image-1.png";
import image2 from "./customer-images/image-2.png";
import image3 from "./customer-images/image-3.png";
import image4 from "./customer-images/image-4.png";
import image5 from "./customer-images/image-5.png";
import image6 from "./customer-images/image-6.png";
import image7 from "./customer-images/image-7.png";
import image8 from "./customer-images/image-8.png";

let custData=[
    {id:1,image:image1,imageName:"YOGIFI - SMART YOGA GADGET",content:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget urna vitae sem blandit rutrum. Vivamus sodales erat magna, scelerisque fermentum enim auctor et. Vestibulum tempus quam ut feugiat pellentesque. Fusce eu aliquet risus. Quisque aliquam nibh sem, ut volutpat justo vulputate vel. Fusce id augue ac massa eleifend efficitur ut a risus. Vestibulum ultricies interdum mauris ut convallis. Fusce scelerisque molestie tellus, ac consequat libero rutrum et. In ac nisi a ex facilisis placerat. Ut aliquet eu nisi in sollicitudin. In tristique hendrerit nunc eu suscipit. Sed feugiat sem vulputate nunc lobortis placerat. Mauris semper orci leo, id lacinia lacus fringilla commodo. In rutrum feugiat ipsum a facilisis. Curabitur feugiat risus vel lacus accumsan, at vehicula orci pellentesque. Nunc cursus nulla accumsan sapien luctus, eu semper magna scelerisque.
    Quisque lacinia egestas nunc, at venenatis ipsum aliquam eu. Praesent commodo suscipit scelerisque. Duis dignissim lacinia eros a porttitor. Nulla ultricies, nibh eu porttitor blandit, ante neque auctor libero, id vehicula tortor est ac mi. Maecenas suscipit tortor id erat mollis, non maximus eros pharetra. Phasellus consequat non lorem blandit tincidunt. Praesent varius velit at feugiat pellentesque. Aenean eleifend venenatis rutrum. Pellentesque non sapien sed nibh bibendum iaculis. Curabitur ut ligula iaculis, suscipit nisi eget, dapibus tellus. Fusce egestas suscipit auctor. Donec gravida mi quis odio faucibus, at fringilla eros dapibus. Aliquam erat volutpat. Proin eleifend faucibus lacus, et molestie est porttitor ac.`},
    {id:2,image:image2,imageName:"EBOUNTI",content:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget urna vitae sem blandit rutrum. Vivamus sodales erat magna, scelerisque fermentum enim auctor et. Vestibulum tempus quam ut feugiat pellentesque. Fusce eu aliquet risus. Quisque aliquam nibh sem, ut volutpat justo vulputate vel. Fusce id augue ac massa eleifend efficitur ut a risus. Vestibulum ultricies interdum mauris ut convallis. Fusce scelerisque molestie tellus, ac consequat libero rutrum et. In ac nisi a ex facilisis placerat. Ut aliquet eu nisi in sollicitudin. In tristique hendrerit nunc eu suscipit. Sed feugiat sem vulputate nunc lobortis placerat. Mauris semper orci leo, id lacinia lacus fringilla commodo. In rutrum feugiat ipsum a facilisis. Curabitur feugiat risus vel lacus accumsan, at vehicula orci pellentesque. Nunc cursus nulla accumsan sapien luctus, eu semper magna scelerisque.
    Quisque lacinia egestas nunc, at venenatis ipsum aliquam eu. Praesent commodo suscipit scelerisque. Duis dignissim lacinia eros a porttitor. Nulla ultricies, nibh eu porttitor blandit, ante neque auctor libero, id vehicula tortor est ac mi. Maecenas suscipit tortor id erat mollis, non maximus eros pharetra. Phasellus consequat non lorem blandit tincidunt. Praesent varius velit at feugiat pellentesque. Aenean eleifend venenatis rutrum. Pellentesque non sapien sed nibh bibendum iaculis. Curabitur ut ligula iaculis, suscipit nisi eget, dapibus tellus. Fusce egestas suscipit auctor. Donec gravida mi quis odio faucibus, at fringilla eros dapibus. Aliquam erat volutpat. Proin eleifend faucibus lacus, et molestie est porttitor ac.`},
    {id:3,image:image3,imageName:"RETAIL HANDYMAN",content:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget urna vitae sem blandit rutrum. Vivamus sodales erat magna, scelerisque fermentum enim auctor et. Vestibulum tempus quam ut feugiat pellentesque. Fusce eu aliquet risus. Quisque aliquam nibh sem, ut volutpat justo vulputate vel. Fusce id augue ac massa eleifend efficitur ut a risus. Vestibulum ultricies interdum mauris ut convallis. Fusce scelerisque molestie tellus, ac consequat libero rutrum et. In ac nisi a ex facilisis placerat. Ut aliquet eu nisi in sollicitudin. In tristique hendrerit nunc eu suscipit. Sed feugiat sem vulputate nunc lobortis placerat. Mauris semper orci leo, id lacinia lacus fringilla commodo. In rutrum feugiat ipsum a facilisis. Curabitur feugiat risus vel lacus accumsan, at vehicula orci pellentesque. Nunc cursus nulla accumsan sapien luctus, eu semper magna scelerisque.
    Quisque lacinia egestas nunc, at venenatis ipsum aliquam eu. Praesent commodo suscipit scelerisque. Duis dignissim lacinia eros a porttitor. Nulla ultricies, nibh eu porttitor blandit, ante neque auctor libero, id vehicula tortor est ac mi. Maecenas suscipit tortor id erat mollis, non maximus eros pharetra. Phasellus consequat non lorem blandit tincidunt. Praesent varius velit at feugiat pellentesque. Aenean eleifend venenatis rutrum. Pellentesque non sapien sed nibh bibendum iaculis. Curabitur ut ligula iaculis, suscipit nisi eget, dapibus tellus. Fusce egestas suscipit auctor. Donec gravida mi quis odio faucibus, at fringilla eros dapibus. Aliquam erat volutpat. Proin eleifend faucibus lacus, et molestie est porttitor ac.`},
    {id:4,image:image4,imageName:"TEMPOSITIONS",content:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget urna vitae sem blandit rutrum. Vivamus sodales erat magna, scelerisque fermentum enim auctor et. Vestibulum tempus quam ut feugiat pellentesque. Fusce eu aliquet risus. Quisque aliquam nibh sem, ut volutpat justo vulputate vel. Fusce id augue ac massa eleifend efficitur ut a risus. Vestibulum ultricies interdum mauris ut convallis. Fusce scelerisque molestie tellus, ac consequat libero rutrum et. In ac nisi a ex facilisis placerat. Ut aliquet eu nisi in sollicitudin. In tristique hendrerit nunc eu suscipit. Sed feugiat sem vulputate nunc lobortis placerat. Mauris semper orci leo, id lacinia lacus fringilla commodo. In rutrum feugiat ipsum a facilisis. Curabitur feugiat risus vel lacus accumsan, at vehicula orci pellentesque. Nunc cursus nulla accumsan sapien luctus, eu semper magna scelerisque.
    Quisque lacinia egestas nunc, at venenatis ipsum aliquam eu. Praesent commodo suscipit scelerisque. Duis dignissim lacinia eros a porttitor. Nulla ultricies, nibh eu porttitor blandit, ante neque auctor libero, id vehicula tortor est ac mi. Maecenas suscipit tortor id erat mollis, non maximus eros pharetra. Phasellus consequat non lorem blandit tincidunt. Praesent varius velit at feugiat pellentesque. Aenean eleifend venenatis rutrum. Pellentesque non sapien sed nibh bibendum iaculis. Curabitur ut ligula iaculis, suscipit nisi eget, dapibus tellus. Fusce egestas suscipit auctor. Donec gravida mi quis odio faucibus, at fringilla eros dapibus. Aliquam erat volutpat. Proin eleifend faucibus lacus, et molestie est porttitor ac.`},
    {id:5,image:image5,imageName:"ALLCARGO LOGISTIC",content:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget urna vitae sem blandit rutrum. Vivamus sodales erat magna, scelerisque fermentum enim auctor et. Vestibulum tempus quam ut feugiat pellentesque. Fusce eu aliquet risus. Quisque aliquam nibh sem, ut volutpat justo vulputate vel. Fusce id augue ac massa eleifend efficitur ut a risus. Vestibulum ultricies interdum mauris ut convallis. Fusce scelerisque molestie tellus, ac consequat libero rutrum et. In ac nisi a ex facilisis placerat. Ut aliquet eu nisi in sollicitudin. In tristique hendrerit nunc eu suscipit. Sed feugiat sem vulputate nunc lobortis placerat. Mauris semper orci leo, id lacinia lacus fringilla commodo. In rutrum feugiat ipsum a facilisis. Curabitur feugiat risus vel lacus accumsan, at vehicula orci pellentesque. Nunc cursus nulla accumsan sapien luctus, eu semper magna scelerisque.
    Quisque lacinia egestas nunc, at venenatis ipsum aliquam eu. Praesent commodo suscipit scelerisque. Duis dignissim lacinia eros a porttitor. Nulla ultricies, nibh eu porttitor blandit, ante neque auctor libero, id vehicula tortor est ac mi. Maecenas suscipit tortor id erat mollis, non maximus eros pharetra. Phasellus consequat non lorem blandit tincidunt. Praesent varius velit at feugiat pellentesque. Aenean eleifend venenatis rutrum. Pellentesque non sapien sed nibh bibendum iaculis. Curabitur ut ligula iaculis, suscipit nisi eget, dapibus tellus. Fusce egestas suscipit auctor. Donec gravida mi quis odio faucibus, at fringilla eros dapibus. Aliquam erat volutpat. Proin eleifend faucibus lacus, et molestie est porttitor ac.`},
    {id:6,image:image6,imageName:"INTA",content:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget urna vitae sem blandit rutrum. Vivamus sodales erat magna, scelerisque fermentum enim auctor et. Vestibulum tempus quam ut feugiat pellentesque. Fusce eu aliquet risus. Quisque aliquam nibh sem, ut volutpat justo vulputate vel. Fusce id augue ac massa eleifend efficitur ut a risus. Vestibulum ultricies interdum mauris ut convallis. Fusce scelerisque molestie tellus, ac consequat libero rutrum et. In ac nisi a ex facilisis placerat. Ut aliquet eu nisi in sollicitudin. In tristique hendrerit nunc eu suscipit. Sed feugiat sem vulputate nunc lobortis placerat. Mauris semper orci leo, id lacinia lacus fringilla commodo. In rutrum feugiat ipsum a facilisis. Curabitur feugiat risus vel lacus accumsan, at vehicula orci pellentesque. Nunc cursus nulla accumsan sapien luctus, eu semper magna scelerisque.
    Quisque lacinia egestas nunc, at venenatis ipsum aliquam eu. Praesent commodo suscipit scelerisque. Duis dignissim lacinia eros a porttitor. Nulla ultricies, nibh eu porttitor blandit, ante neque auctor libero, id vehicula tortor est ac mi. Maecenas suscipit tortor id erat mollis, non maximus eros pharetra. Phasellus consequat non lorem blandit tincidunt. Praesent varius velit at feugiat pellentesque. Aenean eleifend venenatis rutrum. Pellentesque non sapien sed nibh bibendum iaculis. Curabitur ut ligula iaculis, suscipit nisi eget, dapibus tellus. Fusce egestas suscipit auctor. Donec gravida mi quis odio faucibus, at fringilla eros dapibus. Aliquam erat volutpat. Proin eleifend faucibus lacus, et molestie est porttitor ac.`},
    {id:7,image:image7,imageName:"SILK",content:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget urna vitae sem blandit rutrum. Vivamus sodales erat magna, scelerisque fermentum enim auctor et. Vestibulum tempus quam ut feugiat pellentesque. Fusce eu aliquet risus. Quisque aliquam nibh sem, ut volutpat justo vulputate vel. Fusce id augue ac massa eleifend efficitur ut a risus. Vestibulum ultricies interdum mauris ut convallis. Fusce scelerisque molestie tellus, ac consequat libero rutrum et. In ac nisi a ex facilisis placerat. Ut aliquet eu nisi in sollicitudin. In tristique hendrerit nunc eu suscipit. Sed feugiat sem vulputate nunc lobortis placerat. Mauris semper orci leo, id lacinia lacus fringilla commodo. In rutrum feugiat ipsum a facilisis. Curabitur feugiat risus vel lacus accumsan, at vehicula orci pellentesque. Nunc cursus nulla accumsan sapien luctus, eu semper magna scelerisque.
    Quisque lacinia egestas nunc, at venenatis ipsum aliquam eu. Praesent commodo suscipit scelerisque. Duis dignissim lacinia eros a porttitor. Nulla ultricies, nibh eu porttitor blandit, ante neque auctor libero, id vehicula tortor est ac mi. Maecenas suscipit tortor id erat mollis, non maximus eros pharetra. Phasellus consequat non lorem blandit tincidunt. Praesent varius velit at feugiat pellentesque. Aenean eleifend venenatis rutrum. Pellentesque non sapien sed nibh bibendum iaculis. Curabitur ut ligula iaculis, suscipit nisi eget, dapibus tellus. Fusce egestas suscipit auctor. Donec gravida mi quis odio faucibus, at fringilla eros dapibus. Aliquam erat volutpat. Proin eleifend faucibus lacus, et molestie est porttitor ac.`},
    {id:8,image:image8,imageName:"MARTIN’S FAMOUS PASTRY SHOPPE, INC.®",content:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget urna vitae sem blandit rutrum. Vivamus sodales erat magna, scelerisque fermentum enim auctor et. Vestibulum tempus quam ut feugiat pellentesque. Fusce eu aliquet risus. Quisque aliquam nibh sem, ut volutpat justo vulputate vel. Fusce id augue ac massa eleifend efficitur ut a risus. Vestibulum ultricies interdum mauris ut convallis. Fusce scelerisque molestie tellus, ac consequat libero rutrum et. In ac nisi a ex facilisis placerat. Ut aliquet eu nisi in sollicitudin. In tristique hendrerit nunc eu suscipit. Sed feugiat sem vulputate nunc lobortis placerat. Mauris semper orci leo, id lacinia lacus fringilla commodo. In rutrum feugiat ipsum a facilisis. Curabitur feugiat risus vel lacus accumsan, at vehicula orci pellentesque. Nunc cursus nulla accumsan sapien luctus, eu semper magna scelerisque.
    Quisque lacinia egestas nunc, at venenatis ipsum aliquam eu. Praesent commodo suscipit scelerisque. Duis dignissim lacinia eros a porttitor. Nulla ultricies, nibh eu porttitor blandit, ante neque auctor libero, id vehicula tortor est ac mi. Maecenas suscipit tortor id erat mollis, non maximus eros pharetra. Phasellus consequat non lorem blandit tincidunt. Praesent varius velit at feugiat pellentesque. Aenean eleifend venenatis rutrum. Pellentesque non sapien sed nibh bibendum iaculis. Curabitur ut ligula iaculis, suscipit nisi eget, dapibus tellus. Fusce egestas suscipit auctor. Donec gravida mi quis odio faucibus, at fringilla eros dapibus. Aliquam erat volutpat. Proin eleifend faucibus lacus, et molestie est porttitor ac.`},

];

export default custData;